from django.urls import path

from . import views

urlpatterns = [
    path('search_and_download/<str:bounding_point_1>/<str:bounding_point_2>/<str:bounding_point_3>/<str:bounding_point_4>/',
         views.select_and_download_api, name='select_and_download_api'),
    path('download_raw_by_id/<str:id_list>/',
         views.download_raw_by_id, name='download_raw_by_id'),
    path('coreg_image_fetch/',
         views.coreg_image_fetch, name='coreg_image_fetch'),
    path('coreg_submit/<str:master>/<str:slave>/<str:master_swath>/<str:slave_swath>',
         views.coreg_start, name='coreg_start'),
    path('interf_image_fetch/',
         views.interf_image_fetch, name='interf_image_fetch'),
    path('interf_image_generate/<str:master_slave_pair>',
         views.interf_image_generate, name='interf_image_generate'),
    path('deburst_image_fetch/',
         views.deburst_image_fetch, name='deburst_image_fetch'),
    path('deburst_image_generate/<str:master_slave_pair>',
         views.deburst_image_generate, name='deburst_image_generate'),
    path('tpr_image_fetch/',
         views.tpr_image_fetch, name='tpr_image_fetch'),
    path('tpr_image_generate/<str:master_slave_pair>',
         views.tpr_image_generate, name='tpr_image_generate'),
    path('multilooking_image_fetch/',
         views.multilooking_image_fetch, name='multilooking_image_fetch'),
    path('multilooking_image_generate/<str:master_slave_pair>/<int:multilooking_times>',
         views.multilooking_image_generate, name='multilooking_image_generate'),
    path('gpf_image_fetch/',
         views.gpf_image_fetch, name='gpf_image_fetch'),
    path('gpf_image_generate/<str:master_slave_pair>',
         views.gpf_image_generate, name='gpf_image_generate'),
    path('phase_unwrapping_image_fetch/',
         views.phase_unwrapping_image_fetch, name='phase_unwrapping_image_fetch'),
    path('phase_unwrapping_image_generate/<str:master_slave_pair>',
         views.phase_unwrapping_image_generate, name='phase_unwrapping_image_generate'),
    path('p2d_image_fetch/',
         views.p2d_image_fetch, name='p2d_image_fetch'),
    path('p2d_image_generate/<str:master_slave_pair>',
         views.p2d_image_generate, name='p2d_image_generate'),
    path('rdc_image_fetch/',
         views.rdc_image_fetch, name='rdc_image_fetch'),
    path('rdc_image_generate/<str:master_slave_pair>',
         views.rdc_image_generate, name='rdc_image_generate'),
    path('downloading_items/',
         views.get_all_download, name='downloading_items'),
    path('workspace/',
         views.get_workspace, name='workspace'),
    path('tiff_download/<str:tiff_name>',
         views.tiff_download, name='tiff_download'),
]
